# Generated by Django 5.2.3 on 2026-09-19 22:12

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=150)),
                ('national_id', models.CharField(blank=True, default='', max_length=64)),
                ('financial_index', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('school_name', models.CharField(blank=True, default='', max_length=150)),
                ('wilaya', models.CharField(blank=True, default='', max_length=100)),
                ('moughataa', models.CharField(blank=True, default='', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('role', models.CharField(choices=[('TEACHER', 'معلم'), ('ADMIN', 'مدير النظام'), ('SUPERVISOR', 'مفتش تربوي'), ('SUPPORT', 'الدعم الفني')], default='TEACHER', max_length=16)),
                ('account_status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('active', 'نشط'), ('suspended', 'موقوف'), ('disabled', 'معطل'), ('deleted', 'محذوف')], default='pending', max_length=16)),
                ('suspension_reason', models.CharField(blank=True, default='', max_length=255)),
                ('subscription_status', models.CharField(choices=[('TRIAL', 'تجريبي'), ('ACTIVE', 'نشط'), ('EXPIRING_SOON', 'ينتهي قريباً'), ('EXPIRED', 'منتهي'), ('PENDING_VERIFICATION', 'قيد التحقق')], default='TRIAL', max_length=24)),
                ('trial_start_date', models.DateField(default=django.utils.timezone.now)),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('app_pin', models.CharField(blank=True, default='', max_length=8)),
                ('app_lock_enabled', models.BooleanField(default=False)),
                ('color_theme', models.CharField(default='blue', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('ACTIVATE_SUB', 'تفعيل الاشتراك'), ('DEACTIVATE_SUB', 'إلغاء تفعيل الاشتراك'), ('EXTEND_SUB', 'تمديد الاشتراك'), ('END_SUB', 'إنهاء الاشتراك'), ('DISABLE_ACCOUNT', 'تعطيل الحساب'), ('ACTIVATE_ACCOUNT', 'تفعيل الحساب'), ('UPDATE_ROLE', 'تحديث الصلاحية')], max_length=32)),
                ('old_value', models.CharField(blank=True, default='', max_length=255)),
                ('new_value', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
